trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- deployment: DeployToMAG9050
  displayName: Deploy to Deployment Group MAG9050
  environment: 'MAG9050'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'
          workingDirectory: $(System.DefaultWorkingDirectory)  # Make sure you're in the right directory

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'build'  # Relative path to the build output directory
            ArtifactName: 'MyAppArtifact'

        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            WebSiteName: 'YourWebsiteName'  # Replace with your actual IIS website name
            Package: '$(System.DefaultWorkingDirectory)/build/MyAppArtifact.zip'  # Replace with the actual path to your built artifact
            DeploymentGroupName: 'MAG9050'  # Specify your deployment group name
